In [2]:
import os

In [21]:
#Your own path to MLforSTCP
os.chdir(r'C:\Users\ADMIN\Desktop\MLforSTCP')

In [4]:
import faulthandler
faulthandler.enable()
import pandas as pd
from radonpy.ff.gaff2_mod import GAFF2_mod 
from radonpy.ff.descriptor import FF_descriptor

In [5]:
from rdkit import Chem

In [6]:
ff_desc = FF_descriptor(GAFF2_mod(), polar=True)

In [22]:
df=pd.read_csv(r'.\Datasets\Benchmark\smi.csv')
df

,No,ID,SMILES,TC
0,0,PI1,*CC*,0.456185
1,1,PI2,*C(C*)C,0.258773
2,2,PI3,*C(C*)CC,0.264363
3,3,PI4,*C(C*)CCC,0.261131
4,4,PI5,*C(C*)C(C)C,0.234342
...,...,...,...,...
1065,1072,PI1134,*c1ccc(C(c2ccc(-c3nc4cc(-c5ccc6nc(*)[nH]c6c5)c...,0.239876
1066,1073,PI1135,*c1ccc(C(c2ccc(-c3nc4ccc(-c5ccc6nc(*)[nH]c6c5)...,0.248861
1067,1074,PI1136,*c1cccc(S(=O)(=O)NCCCCCCNS(*)(=O)=O)c1,0.208098
1068,1075,PI1137,*c1ccc(S(*)(=O)=O)cc1,0.199093
1069,1076,PI1138,*Cc1cc(*)c(O)cc1C,0.226688

In [8]:
mp = 20 # parallel number 
n = 10 # cyclic oligomerization for polymer 
nk = 80 # number of Gaussian in discretization (Hyperparameter) 
sigma = 1/nk/2 # band width of Gaussian kernel (Hyperparameter) 
mu = None # list of discretizing points (Hyperparameter) 
ff_desc = FF_descriptor(GAFF2_mod(), polar=True) 
smiles_list=df['SMILES']
desc = ff_desc.ffkm_mp(smiles_list, mp=mp, nk=nk, s=sigma, mu=mu, cyclic=n) 
desc_names = ff_desc.ffkm_desc_names(nk=nk) 
FFKM_data = pd.DataFrame(desc, columns=desc_names)

In [9]:
FFKM_data

,mass_H,mass_C,mass_N,mass_O,mass_F,mass_P,mass_S,mass_Cl,mass_Br,mass_I,...,k_dih_70,k_dih_71,k_dih_72,k_dih_73,k_dih_74,k_dih_75,k_dih_76,k_dih_77,k_dih_78,k_dih_79
0,0.739014,0.478028,0.396042,0.311840,0.191260,0.003575,0.002086,0.000325,1.830063e-26,1.524166e-73,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.739014,0.478028,0.396042,0.311840,0.191260,0.003575,0.002086,0.000325,1.830063e-26,1.524166e-73,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.739014,0.478028,0.396042,0.311840,0.191260,0.003575,0.002086,0.000325,1.830063e-26,1.524166e-73,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.739014,0.478028,0.396042,0.311840,0.191260,0.003575,0.002086,0.000325,1.830063e-26,1.524166e-73,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.739014,0.478028,0.396042,0.311840,0.191260,0.003575,0.002086,0.000325,1.830063e-26,1.524166e-73,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,0.415810,0.718493,0.688310,0.615030,0.451879,0.025425,0.017123,0.004314,5.118764e-22,1.693690e-65,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1066,0.415810,0.718493,0.688310,0.615030,0.451879,0.025425,0.017123,0.004314,5.118764e-22,1.693690e-65,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1067,0.554641,0.555102,0.510087,0.443512,0.317039,0.062834,0.059515,0.046897,1.515816e-14,2.708286e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1068,0.416893,0.654673,0.622982,0.552476,0.400711,0.089796,0.085726,0.068309,2.215423e-14,3.958265e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1069,0.576177,0.620853,0.559267,0.471456,0.314601,0.008513,0.005205,0.000955,2.477998e-24,2.314734e-69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
pd.DataFrame(df.iloc[:,3]).join(FFKM_data).to_csv(r'.\Datasets\Benchmark\FF_80.csv')