In [ ]:
#Taking virtual synthesis of polyolefins as an example
import numpy as np
import pandas as pd
import time
import pickle
from smipoly.smip import monc, polg
import os

In [2]:
#Your own path to MLforSTCP
os.chdir(r'C:\Users\ADMIN\Desktop\MLforSTCP')

In [4]:
#read source file
DF1 = pd.read_csv(r".\Datasets\Reaction\monomer_Sample_10000.csv",index_col=0).drop_duplicates(subset='SMILES') #sample monomer list on GitHub  
DF1

,SMILES,smip_cand_mons,vinyl,epo,cOle,lactone,lactam,hydCOOH,aminCOOH,hindPhenol,...,sfonediX,BzodiF,diepo,diCOOH,diol,diamin,diNCO,dicAnhyd,pridiamin,diol_b
42511,C=C1CC(S(=O)(=O)c2ccccc2)C1,C=C1CC(S(=O)(=O)c2ccccc2)C1,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
613,Cc1c(Br)c[nH]c(=O)c1Br,Cc1c(Br)c[nH]c(=O)c1Br,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
47676,C=Cc1ccc(C)cc1F,C=Cc1ccc(C)cc1F,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
75118,N#Cc1cccc(OCC#CCCl)c1Br,N#Cc1cccc(OCC#CCCl)c1Br,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21889,O=C1OC(CO)C(O)C1F,O=C1OC(CO)C(O)C1F,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63221,C=CCOCCC,C=CCOCCC,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
75756,CC(C)OC(=O)C(C)NCC#C[Si](C)(C)C,CC(C)OC(=O)C(C)NCC#C[Si](C)(C)C,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
59640,COC(=O)C=Cc1cccc(NC(C)=O)c1,COC(=O)C=Cc1cccc(NC(C)=O)c1,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26846,Cc1cc(C)c(O)c(O)c1C,Cc1cc(C)c(O)c(O)c1C,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
62583,C=CCCCNCCO[Si](C)(C)C(C)(C)C,C=CCCCNCCO[Si](C)(C)C(C)(C)C,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
#Taking virtual synthesis of polyolefins as an example
tpstart = time.perf_counter()
DF03 = polg.biplym(df=DF1, targ=['polyolefin', ], Pmode='a', dsp_rsl=True)
tpend = time.perf_counter()
tm = tpend-tpstart
print("CPU time: ", tm)
print(f"DF03 memory usage: {DF03.memory_usage(deep=True).sum() / 1024 ** 2} MB")

run at advanced mode
number of polymerization reactions =  3018340
number of generated polymers =  6405753
CPU time:  4203.0489459
DF03 memory usage: 2218.0469970703125 MB

In [13]:
DF03

,mon1,mon2,polym,polymer_class,reactset
0,C=C1CC(S(=O)(=O)c2ccccc2)C1,,*CC1(*)CC(S(=O)(=O)c2ccccc2)C1,polyolefin,"(, C=C1CC(S(=O)(=O)c2ccccc2)C1)"
1,C=Cc1ccc(C)cc1F,,*CC(*)c1ccc(C)cc1F,polyolefin,"(, C=Cc1ccc(C)cc1F)"
2,C=C(C(=O)O)c1cccc(Cl)c1Cl,,*CC(*)(C(=O)O)c1cccc(Cl)c1Cl,polyolefin,"(, C=C(C(=O)O)c1cccc(Cl)c1Cl)"
3,C=CC(O)c1ccc(Br)cn1,,*CC(*)C(O)c1ccc(Br)cn1,polyolefin,"(, C=CC(O)c1ccc(Br)cn1)"
4,C=CCN(CC=C)N=Nc1cccc(Cl)c1,,*CC(*)CN(CC(*)C*)N=Nc1cccc(Cl)c1,polyolefin,"(, C=CCN(CC=C)N=Nc1cccc(Cl)c1)"
...,...,...,...,...,...
6405748,C=CCCCNCCO[Si](C)(C)C(C)(C)C,CCOC(=O)N1CC2C=CC1CC2,*CC(CCCNCCO[Si](C)(C)C(C)(C)C)C1C(*)C2CCC1N(C(...,polyolefin,"(C=CCCCNCCO[Si](C)(C)C(C)(C)C, CCOC(=O)N1CC2C=..."
6405749,C=CCCCNCCO[Si](C)(C)C(C)(C)C,CCOC(=O)N1CC2C=CC1CC2,*C(CCCNCCO[Si](C)(C)C(C)(C)C)CC1C2CCC(C1*)N(C(...,polyolefin,"(C=CCCCNCCO[Si](C)(C)C(C)(C)C, CCOC(=O)N1CC2C=..."
6405750,C=CCCCNCCO[Si](C)(C)C(C)(C)C,CCOC(=O)N1CC2C=CC1CC2,*C(CCCNCCO[Si](C)(C)C(C)(C)C)CC1C(*)C2CCC1N(C(...,polyolefin,"(C=CCCCNCCO[Si](C)(C)C(C)(C)C, CCOC(=O)N1CC2C=..."
6405751,C=CCCCNCCO[Si](C)(C)C(C)(C)C,O=C1CC2C=CC(C1)N2,*CC(CCCNCCO[Si](C)(C)C(C)(C)C)C1C2CC(=O)CC(N2)C1*,polyolefin,"(C=CCCCNCCO[Si](C)(C)C(C)(C)C, O=C1CC2C=CC(C1)N2)"
6405752,C=CCCCNCCO[Si](C)(C)C(C)(C)C,O=C1CC2C=CC(C1)N2,*C(CCCNCCO[Si](C)(C)C(C)(C)C)CC1C2CC(=O)CC(N2)C1*,polyolefin,"(C=CCCCNCCO[Si](C)(C)C(C)(C)C, O=C1CC2C=CC(C1)N2)"

In [14]:
#extract linear polymer
DF04 = DF03[DF03['polym'].apply(lambda x:x.count('*')==2)]
DF05 = DF04.drop_duplicates(subset=['polym'])
DF05

,mon1,mon2,polym,polymer_class,reactset
0,C=C1CC(S(=O)(=O)c2ccccc2)C1,,*CC1(*)CC(S(=O)(=O)c2ccccc2)C1,polyolefin,"(, C=C1CC(S(=O)(=O)c2ccccc2)C1)"
1,C=Cc1ccc(C)cc1F,,*CC(*)c1ccc(C)cc1F,polyolefin,"(, C=Cc1ccc(C)cc1F)"
2,C=C(C(=O)O)c1cccc(Cl)c1Cl,,*CC(*)(C(=O)O)c1cccc(Cl)c1Cl,polyolefin,"(, C=C(C(=O)O)c1cccc(Cl)c1Cl)"
3,C=CC(O)c1ccc(Br)cn1,,*CC(*)C(O)c1ccc(Br)cn1,polyolefin,"(, C=CC(O)c1ccc(Br)cn1)"
5,C=CCC(NC(=O)OCc1ccccc1)B1OC(C)(C)C(C)(C)O1,,*CC(*)CC(NC(=O)OCc1ccccc1)B1OC(C)(C)C(C)(C)O1,polyolefin,"(, C=CCC(NC(=O)OCc1ccccc1)B1OC(C)(C)C(C)(C)O1)"
...,...,...,...,...,...
6405748,C=CCCCNCCO[Si](C)(C)C(C)(C)C,CCOC(=O)N1CC2C=CC1CC2,*CC(CCCNCCO[Si](C)(C)C(C)(C)C)C1C(*)C2CCC1N(C(...,polyolefin,"(C=CCCCNCCO[Si](C)(C)C(C)(C)C, CCOC(=O)N1CC2C=..."
6405749,C=CCCCNCCO[Si](C)(C)C(C)(C)C,CCOC(=O)N1CC2C=CC1CC2,*C(CCCNCCO[Si](C)(C)C(C)(C)C)CC1C2CCC(C1*)N(C(...,polyolefin,"(C=CCCCNCCO[Si](C)(C)C(C)(C)C, CCOC(=O)N1CC2C=..."
6405750,C=CCCCNCCO[Si](C)(C)C(C)(C)C,CCOC(=O)N1CC2C=CC1CC2,*C(CCCNCCO[Si](C)(C)C(C)(C)C)CC1C(*)C2CCC1N(C(...,polyolefin,"(C=CCCCNCCO[Si](C)(C)C(C)(C)C, CCOC(=O)N1CC2C=..."
6405751,C=CCCCNCCO[Si](C)(C)C(C)(C)C,O=C1CC2C=CC(C1)N2,*CC(CCCNCCO[Si](C)(C)C(C)(C)C)C1C2CC(=O)CC(N2)C1*,polyolefin,"(C=CCCCNCCO[Si](C)(C)C(C)(C)C, O=C1CC2C=CC(C1)N2)"
6405752,C=CCCCNCCO[Si](C)(C)C(C)(C)C,O=C1CC2C=CC(C1)N2,*C(CCCNCCO[Si](C)(C)C(C)(C)C)CC1C2CC(=O)CC(N2)C1*,polyolefin,"(C=CCCCNCCO[Si](C)(C)C(C)(C)C, O=C1CC2C=CC(C1)N2)"

In [ ]:
DF05.to_csv(r'.\Datasets\Reaction\polyolefin.csv')