In [3]:
import pandas as pd
import numpy as np
import pickle
import os

In [2]:
from tensorflow.keras.models import Sequential, save_model, load_model

In [4]:
#Your own path to MLforSTCP
os.chdir(r'C:\Users\ADMIN\Desktop\MLforSTCP')

In [5]:
FFNN=load_model(r'.\Datasets\ML_model\FFNN.model')

In [6]:
FFNN.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 480)               350880
_________________________________________________________________
dense_1 (Dense)              (None, 416)               200096
_________________________________________________________________
dropout (Dropout)            (None, 416)               0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 417
=================================================================
Total params: 551,393
Trainable params: 551,393
Non-trainable params: 0
_________________________________________________________________

In [7]:
CNN=load_model(r'.\Datasets\ML_model\CNN.model')

WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.

In [8]:
CNN.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d (Conv2D)              (None, 71, 71, 32)        3232
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 64, 64, 32)        65568
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 63, 63, 16)        2064
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 31, 31, 16)        0
_________________________________________________________________
dropout (Dropout)            (None, 31, 31, 16)        0
_________________________________________________________________
flatten (Flatten)            (None, 15376)             0
_________________________________________________________________
dense (Dense)                (None, 1)                 15377
=================================================================
Total params: 86,241
Trainable params: 86,241
Non-trainable params: 0
_________________________________________________________________

In [9]:
df_Polyolefins=pd.read_csv(r'.\Datasets\Reaction\FF_polyester.csv',index_col=0)
df_Polyolefins

,mass_H,mass_C,mass_N,mass_O,mass_F,mass_P,mass_S,mass_Cl,mass_Br,mass_I,...,k_dih_70,k_dih_71,k_dih_72,k_dih_73,k_dih_74,k_dih_75,k_dih_76,k_dih_77,k_dih_78,k_dih_79
0,0.586280,0.551962,0.495846,0.421087,0.290178,0.049981,0.047218,0.037123,1.200021e-14,2.144060e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.430951,0.714470,0.688150,0.616609,0.449093,0.017500,0.011060,0.002237,8.802163e-24,8.283756e-69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.517556,0.672270,0.618029,0.528918,0.359004,0.010291,0.006328,0.001181,3.363488e-24,3.147983e-69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.418439,0.723573,0.702422,0.632913,0.462603,0.017269,0.010833,0.002136,6.679996e-24,6.075353e-69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.647558,0.548222,0.482761,0.402318,0.267804,0.007709,0.004750,0.000892,2.626010e-24,2.459347e-69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11364,0.616519,0.521925,0.465088,0.394061,0.272583,0.048083,0.045406,0.035659,1.152020e-14,2.058298e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11365,0.513097,0.622694,0.577700,0.501857,0.352463,0.045128,0.041404,0.031160,9.931207e-15,1.774394e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11366,0.580109,0.529365,0.476376,0.406738,0.285013,0.070783,0.068257,0.055207,1.800031e-14,3.216090e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11367,0.508366,0.617599,0.573092,0.498612,0.352385,0.052024,0.048206,0.036769,1.175531e-14,2.100304e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11368,0.508366,0.617599,0.573092,0.498612,0.352385,0.052024,0.048206,0.036769,1.175531e-14,2.100304e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df2=df_Polyolefins.dropna(subset=['mass_H'])
df2

,mass_H,mass_C,mass_N,mass_O,mass_F,mass_P,mass_S,mass_Cl,mass_Br,mass_I,...,k_dih_70,k_dih_71,k_dih_72,k_dih_73,k_dih_74,k_dih_75,k_dih_76,k_dih_77,k_dih_78,k_dih_79
0,0.586280,0.551962,0.495846,0.421087,0.290178,0.049981,0.047218,0.037123,1.200021e-14,2.144060e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.430951,0.714470,0.688150,0.616609,0.449093,0.017500,0.011060,0.002237,8.802163e-24,8.283756e-69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.517556,0.672270,0.618029,0.528918,0.359004,0.010291,0.006328,0.001181,3.363488e-24,3.147983e-69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.418439,0.723573,0.702422,0.632913,0.462603,0.017269,0.010833,0.002136,6.679996e-24,6.075353e-69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.647558,0.548222,0.482761,0.402318,0.267804,0.007709,0.004750,0.000892,2.626010e-24,2.459347e-69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11364,0.616519,0.521925,0.465088,0.394061,0.272583,0.048083,0.045406,0.035659,1.152020e-14,2.058298e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11365,0.513097,0.622694,0.577700,0.501857,0.352463,0.045128,0.041404,0.031160,9.931207e-15,1.774394e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11366,0.580109,0.529365,0.476376,0.406738,0.285013,0.070783,0.068257,0.055207,1.800031e-14,3.216090e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11367,0.508366,0.617599,0.573092,0.498612,0.352385,0.052024,0.048206,0.036769,1.175531e-14,2.100304e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11368,0.508366,0.617599,0.573092,0.498612,0.352385,0.052024,0.048206,0.036769,1.175531e-14,2.100304e-51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
finger=[]
sigma=80
for k in range(len(df_Polyolefins)):
    desc=np.zeros(sigma).reshape(1,-1)
    data=df_Polyolefins.iloc[k].values
    for i in range(10):
        desc[0][i]=data[i]
    desc1=data[10:].reshape(-1,sigma)
    desc2=np.zeros(sigma*(sigma-10)).reshape(-1,sigma)
    finger.append(np.vstack([desc,desc1,desc2]))
finger=np.array(finger)

In [13]:
finger_shape=finger.shape
finger1=finger.reshape(finger_shape[0],finger_shape[1],finger_shape[2],1)

In [16]:
TC_CNN=CNN.predict(finger1)

In [17]:
TC_FFNN=FFNN.predict(df2)

In [22]:
df_res=pd.DataFrame(TC_CNN,columns=['CNN']).join(pd.DataFrame(TC_FFNN,columns=['FFNN']))
df_res

            CNN      FFNN
0      0.114436  0.174673
1      0.216721  0.212616
2      0.227165  0.203005
3      0.264022  0.279097
4      0.177388  0.206848
...         ...       ...
11364  0.214930  0.234151
11365  0.208667  0.242861
11366  0.175189  0.233324
11367  0.225558  0.233971
11368  0.225558  0.233971

[11369 rows x 2 columns]